### ISSUE TITLE
Update dead links

### ISSUE THREAD

**Issue by phiedw** [farao-community/farao-community.github.io#83]
A few links are currently broken:
or-tools
json parameters
powsybl documentation
maybe others

**Comment by pet-mit** [comment]
Here is an automatic way of detecting broken links:
![image](https://github.com/farao-community/farao-community.github.io/assets/47452063/8a671f96-6ef5-4cb6-a103-8f18b4f2e2ed)

I already did some cleanup in [this PR](https://github.com/farao-community/farao-community.github.io/pull/110), but there is a lot of work still to be done

**Comment by pet-mit** [comment]
fixed everything here : https://github.com/farao-community/farao-community.github.io/pull/110
